#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Sep 12 11:49:29 +0530 2025
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 9e1b950945844b1eacd44b8fd52c58d6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_MiniRiscV_behav xil_defaultlib.tb_MiniRiscV xil_defaultlib.glbl -log elaborate.log"
xelab -wto 9e1b950945844b1eacd44b8fd52c58d6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_MiniRiscV_behav xil_defaultlib.tb_MiniRiscV xil_defaultlib.glbl -log elaborate.log

