#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Sep 12 11:49:30 +0530 2025
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_MiniRiscV_behav -key {Behavioral:sim_1:Functional:tb_MiniRiscV} -tclbatch tb_MiniRiscV.tcl -view /home/thishakyabb/Documents/skill_surf/mini_processor/sim/Waveforms/MiniRiscV_tb_behav.wcfg -view /home/thishakyabb/Documents/skill_surf/mini_processor/sim/Waveforms/MiniRiscV_tb_with_ram_behav.wcfg -log simulate.log"
xsim tb_MiniRiscV_behav -key {Behavioral:sim_1:Functional:tb_MiniRiscV} -tclbatch tb_MiniRiscV.tcl -view /home/thishakyabb/Documents/skill_surf/mini_processor/sim/Waveforms/MiniRiscV_tb_behav.wcfg -view /home/thishakyabb/Documents/skill_surf/mini_processor/sim/Waveforms/MiniRiscV_tb_with_ram_behav.wcfg -log simulate.log

